; Inhero MR-2 - nRF52840 based LoRa node with SX1262, SSD1306 OLED, RV-3028 RTC
; Based on RAK4630 module with custom carrier board
[env:inhero_mr2]
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = PRIVATE_HW
custom_meshtastic_architecture = nrf52840
custom_meshtastic_display_name = Inhero MR-2
custom_meshtastic_tags = Inhero

extends = nrf52840_base
board = inhero_mr2
board_level = extra
board_check = true
build_type = release
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/inhero_mr2
  -D INHERO_MR2
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
build_src_filter = ${nrf52_base.build_src_filter}
  +<../variants/nrf52840/inhero_mr2>
lib_deps =
  ${nrf52840_base.lib_deps}
  melopero/Melopero RV3028@1.2.0

upload_protocol = nrfutil
